# Site settings
title: "آهنگ‌کده"
description: "آهنگ‌ها"
podcast-description: "آهنگ‌ها"
url:  "https:/music.mhkarami97.ir" # Actual base url of the website
baseurl: "/"                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Mohammad Hossein Karami"
  email: "mhkarami97@gmail.com"
  url: "https://mhkarami97.ir"
permalink: pretty
permalink: /:title
keywords: [podcast, jekyll]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 20
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username: mhkarami97
  card: summary
facebook:
  app_id: 
logo: /assets/img/Podcast_Cover.png
social:
  name: mhkarami97
  links:
    - https://mhkarami97.ir/
lang: fa

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
podcast_title: Music
podcast_author: Mohammad Hissein Karami
podcast_email: mhkarami97@gmail.com
podcast_subtitle: "آهنگ‌کده"
podcast_summary: "آهنگ‌کده"
podcast_description: "آهنگ‌کده"
podcast_explicit: "no"
podcast_type: serial 
podcast_lang: fa
podcast_launch: "2023-04-27" #Launch date of your podcast
podcast_copyright: "&#xA9;mhkarami97"
podcast_feed: 
podcast_artwork: "/assets/img/Podcast_Cover.png"