analytics-id: 
#Pages
pages:
  - {name: 'لیست', link: 'episodes.html'}
  - {name: 'دسته‌بندی', link: 'categories'}

social:
  - {icon: 'envelope', type: "solid", link: 'mailto:mhkarami97@gmail.com'}

websites-podcast:
  - {name: 'mhkarami97', link: 'https://mhkarami97.ir'}

translate-date: true #See _includes/date.html to translate the months' name
shownotes: false

#Disqus
disqus:
  disqus_shortname: 